<template>
  <div class="loader catalog__loader">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      style="
        margin: auto;
        display: block;
        shape-rendering: auto;
        animation-play-state: running;
        animation-delay: 0s;
      "
      width="497px"
      height="497px"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <rect
        x="18"
        y="24"
        width="14"
        height="52"
        fill="#9eff00"
        style="animation-play-state: running; animation-delay: 0s"
      >
        <animate
          attributeName="y"
          repeatCount="indefinite"
          dur="0.7042253521126761s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="3.1999999999999957;24;24"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.14084507042253522s"
          style="animation-play-state: running; animation-delay: 0s"
        ></animate>
        <animate
          attributeName="height"
          repeatCount="indefinite"
          dur="0.7042253521126761s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="93.60000000000001;52;52"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.14084507042253522s"
          style="animation-play-state: running; animation-delay: 0s"
        ></animate>
      </rect>
      <rect
        x="43"
        y="24"
        width="14"
        height="52"
        fill="#9eff00"
        style="animation-play-state: running; animation-delay: 0s"
      >
        <animate
          attributeName="y"
          repeatCount="indefinite"
          dur="0.7042253521126761s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="8.399999999999999;24;24"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.07042253521126761s"
          style="animation-play-state: running; animation-delay: 0s"
        ></animate>
        <animate
          attributeName="height"
          repeatCount="indefinite"
          dur="0.7042253521126761s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="83.2;52;52"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.07042253521126761s"
          style="animation-play-state: running; animation-delay: 0s"
        ></animate>
      </rect>
      <rect
        x="68"
        y="24"
        width="14"
        height="52"
        fill="#9eff00"
        style="animation-play-state: running; animation-delay: 0s"
      >
        <animate
          attributeName="y"
          repeatCount="indefinite"
          dur="0.7042253521126761s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="8.399999999999999;24;24"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          style="animation-play-state: running; animation-delay: 0s"
        ></animate>
        <animate
          attributeName="height"
          repeatCount="indefinite"
          dur="0.7042253521126761s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="83.2;52;52"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          style="animation-play-state: running; animation-delay: 0s"
        ></animate>
      </rect>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>
  </div>
</template>

<style>
.catalog__loader {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 5;
}
</style>
